config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get 'users/index'
  get 'facebook_movies/index'
  
  resources :reviews
  resources :posts
  resources :watched_movies
  resources :comments, only: [:create, :destroy]
  
  devise_for :users,  :controllers => { :omniauth_callbacks => "callbacks" } do 
    member do
      get :followers
    end
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  
  resources :users
  get 'welcome/index'
  get 'home/index'
  get 'imdb_movies/index'
  get 'imdb_movies/show'
  
  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :watch, to: 'watched_movies#create', as: :watch, via: :post

   root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  

  belongs_to :user
  counter_culture :user
  acts_as_votable
  acts_as_commentable

  include PublicActivity::Model
  tracked only: [:create, :like], owner: Proc.new{ |controller, model| model.user }

  default_scope -> { order('created_at DESC') }

  mount_uploader :attachment, AvatarUploader


  validates_presence_of :content
  validates_presence_of :user

  auto_html_for :content do
    html_escape
    image
    youtube(width: 400, height: 250, autoplay: true)
    link target: '_blank', rel: 'nofollow'
    simple_format
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = current_user.posts
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      redirect_to posts_path, notice: @post.errors.full_messages.first
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to posts_path }
    end 
  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit( :content, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="info">

  <h3><strong><%= link_to post.user.name, user_path(post.user) %></strong>
  <span class="action">created a <%= link_to 'post', post %></span>
</div></h3>
<div class="content">
  <span class="text"><%= post.content %></span>
  
  <div class="points">
    <span class="like-count"><%= pluralize(post.get_likes.size, 'like') %></span>
    <span class="comments-count"><%= pluralize(post.comments.size, 'comment') %></span>
    <div class="pull-right">
      <% if belongs_to_user?(post) %>
        <%= link_to edit_post_path(post), class: 'btn btn-primary btn-sm' do %>
          <% fa_icon 'pencil' %>
        <% end %>
        <%= link_to post_path(post), method: :delete, class:'btn btn-danger btn-sm' do %>
          <% fa_icon 'trash' %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
 <hr>
<%= render 'shared/actions', resource: post %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table class=" table table-hover">
  <thead>
    <tr>

      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= post.user.name %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="authform">
  <%= form_for(@post) do |f| %>
    <div class="form-group">
      <%= f.label 'Update status' %><br>
        <%= f.text_area :content, class: 'form-control', autofocus: true, 
            placeholder: 'What\'s up?' %>

    </div>
    <%= f.submit :post, class: 'btn btn-primary'%>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div id="post-<%= @post.id %>" >


<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

 <h4>Comments</h4>
  <hr>
<%= render 'comments/form', commentable: @post %>
<hr>
<div class="comments">
        <%= render(@comments) || render('shared/no_resources', resources: 'Comments') %>
</div>
</div>